### PR TITLE
Ensure traces start with a `PSB+` packet sequence.

### LINKED ISSUE #41: Really small traces will fail to decode.
I've noticed that in the simple example, if `iters` is less than about 55, then often the trace will not decode properly and libipt flags "expected tracing turned on event".

Not sure why this might be.

### PR DESCRIPTION
**Pull request by vext01**
This is the first of a few fixes coming in to make the trace decoding branch work.

This fixes #41. Please see the issue for a description of why this change is required.

The doc test change is weird. Only after the first commit does it crash. It should have been crashing all along. For what reason, I don't know. Anyway, it's fixed now.

OK?

### CODE REVIEW

**Comment by vext01** [comment]
Branch synced.

File: src/backends/perf_pt/collect.c [hunk 1]
```diff
@@ -570,8 +570,9 @@ perf_pt_free_tracer(struct tracer_ctx *tr_ctx) {
     if (tr_ctx->stop_fds[0] != -1) {
         close(tr_ctx->stop_fds[0]);
     }
-    if (tr_ctx->perf_fd) {
+    if (tr_ctx->perf_fd >= 0) {
         close(tr_ctx->perf_fd);
+        tr_ctx->perf_fd = -1;
```
Comment (ltratt) [inline src/backends/perf_pt/collect.c]: Do we know for sure that valid fds have to be `>=` 0?

File: src/backends/perf_pt/mod.rs [hunk 2]
```diff
@@ -277,12 +275,20 @@ impl Tracer for PerfPTTracer {
             return Err(HWTracerError::TracerAlreadyStarted);
         }
 
+        // At the time of writing, we have to use a fresh Perf file descriptor to ensure traces
```
Comment (ltratt) [inline src/backends/perf_pt/mod.rs]: I think the second sentence ("this is required") is redundant?

**Comment by ltratt** [comment]
Am an I an idiot if I say that I can't see where this PR closes a file handle?

File: src/backends/perf_pt/collect.c (hunk 1 above)
Comment (vext01) [reply src/backends/perf_pt/collect.c]: Since open returns -1 on error...

Comment (ltratt) [reply src/backends/perf_pt/collect.c]: Ah, even more to the point the OpenBSD `open` page says "If successful, open() returns a non-negative integer, termed a file descriptor." Just checking!

**Comment by vext01** [comment]
It's here:
https://github.com/softdevteam/hwtracer/blob/5bb7c9a3b9727c22f2100be3c911ec3f22d9e18e/src/backends/perf_pt/collect.c#L573-L575

And the call to `perf_pt_free_tracer` was moved here:
https://github.com/softdevteam/hwtracer/blob/5bb7c9a3b9727c22f2100be3c911ec3f22d9e18e/src/backends/perf_pt/mod.rs#L311-L313

i.e. when we stop tracing, not when we destroy the tracer.

**Comment by ltratt** [comment]
Aha, OK.

File: src/backends/perf_pt/mod.rs (hunk 2 above)
Comment (vext01) [reply src/backends/perf_pt/mod.rs]: I think it's OK as-is. A trace not starting with a `PSB+` is a valid trace, but it may not decode.

Comment (ltratt) [reply src/backends/perf_pt/mod.rs]: How can it be valid if it can't be decoded?

Comment (vext01) [reply src/backends/perf_pt/mod.rs]: There are many levels. The packets decoder would succeed, but the instruction and block decoders would not.

Comment (vext01) [reply src/backends/perf_pt/mod.rs]: So it's a valid trace at the packet level, if you see what I mean?

Comment (ltratt) [reply src/backends/perf_pt/mod.rs]: Ah, so maybe we need to say which decoder wouldn't work in the comment?

**Comment by vext01** [comment]
Try this.

File: src/backends/perf_pt/mod.rs [hunk 3]
```diff
@@ -276,8 +276,8 @@ impl Tracer for PerfPTTracer {
         }
 
         // At the time of writing, we have to use a fresh Perf file descriptor to ensure traces
-        // start with a `PSB+` packet sequence. This is required for correct decoding. For this
-        // reason we have to re-initialise for each new tracing session.
+        // start with a `PSB+` packet sequence. This is required for correct instruction- and
```
Comment (ltratt) [inline src/backends/perf_pt/mod.rs]: On second reading I know why the "-" is at the end of "instruction" -- but it's pretty distracting. I think it's safe enough to just drop it.

Comment (vext01) [reply src/backends/perf_pt/mod.rs]: We even have enough space on the line to repeat `-level`. Looks good?

**Comment by ltratt** [comment]
Yep, let's squash.

**Comment by vext01** [comment]
splat.

**Comment by ltratt** [comment]
Should the 1st and 3rd commits be squashed together?

**Comment by vext01** [comment]
I think they are separate issues. The close logic was wrong in master too.

**Comment by ltratt** [comment]
OK.
